### ISSUE TITLE
checking sdk-binary-tools versions

### ISSUE THREAD

**Issue by tomkraw1** [OSTC/php-sdk-binary-tools#1]
It would be nice if compilation of PHP and/or extensions was equipped with some kind of versions check. Configure system should detect unsupported versions of binaries.

I had a problem with compilation because I had another instance of bison and others tools on my computer. Some more details on the newslist http://news.php.net/php.pecl.dev/11459.

**Comment by weltling** [comment]
Finally - SDK 2.0.0 allows to implement this, yet in the base form, for master. With this - done.

Thanks.
