### ISSUE TITLE
'-h' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by madorin** [OSTC/php-sdk-binary-tools#10]
buildconf -> ok
configure --disable-all --enable-cli ->ok
nmake -> error.

It seems in quotes it should be some command, but it is empty now :(

D:\Projects\Php\phpdev\vc15\x64
$ nmake

Microsoft (R) Program Maintenance Utility Version 14.10.25019.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Recreating build dirs
        type ext\pcre\php_pcre.def > D:\Projects\Php\phpdev\vc15\x64\x64\Release_TS\php7ts.dll.def
        "" -h win32\ -r D:\Projects\Php\phpdev\vc15\x64\x64\Release_TS\ -x D:\Projects\Php\phpdev\vc15\x64\x64\Release_TS\ win32\build\wsyslog.mc
'-h' is not recognized as an internal or external command,
operable program or batch file.
NMAKE : fatal error U1077: '"' : return code '0x1'
Stop.

**Comment by madorin** [comment]
oki, it did not found mt & mt.exe due to custom VC installation during VS setup. question closed.

**Comment by weltling** [comment]
nice :)

**Comment by robsonpiere** [comment]
@madorin Was it necessary to reinstall VC ++?

**Comment by madorin** [comment]
@robsonpiere , run the setup again and include more options... it seems i installed it customized and just picked a few options, which i considered enough.
