### ISSUE TITLE
Deps for PHP 7.2 unavailable

### ISSUE THREAD

**Issue by macintoshplus** [OSTC/php-sdk-binary-tools#15]
The package `deps-7.2-vc15-x64.7z` and `deps-7.2-vc15-x86.7z` is not available on `http://windows.php.net/downloads/php-sdk/`.

I need this for build automatically PHP's extensions for Windows with appveyor.

**Comment by weltling** [comment]
Thanks for the report. You can use the `phpsdk_deps` tool as in readme, to fetch the dependencies. Perhaps it would also make sense to extend the tool to keep providing the full dependencies package.

Thanks.

**Comment by weltling** [comment]
@macintoshplus the matter is now cleared out. The 7z packages for 5.6, 7.0 and 7.1 are still provided. For 7.2 please used the new SDK tools to fetch the dependencies.

Thanks.
