### ISSUE TITLE
Unable to compile due to compiler version mismatch (iconv?)

### ISSUE THREAD

**Issue by Wes1262** [OSTC/php-sdk-binary-tools#17]
> mismatch between 'P1' version '20161212' and 'P2' version '20150812'

Seems  one of the dependencies is compiled using VC14

Last thing i get before the error is:

```
libiconv_a.lib(iconv1.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
fatal error C1900: Il mismatch between 'P1' version '20161212' and 'P2' version '20150812'
LINK : fatal error LNK1257: code generation failed
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\link.exe"' : return code '0x4e9'
Stop.
```

If I do `--without-libxml  --without-iconv` everything works correctly. (Why on earth is iconv a dependency to libxml?)

This happens both with 7.2 branch and master.

**Comment by Wes1262** [comment]
```
configure 
--enable-apache2-4handler 
--enable-phpdbg 
--disable-test-ini 
--disable-cgi 
--disable-phpdbg-webhelper 
--with-analyzer 
--enable-mbstring 
--enable-intl 
--disable-phar 
--disable-xmlreader 
--disable-xmlwriter 
--disable-ipv6 
--disable-calendar 
--disable-com-dotnet 
--disable-ctype 
--disable-filter 
--disable-hash 
--disable-session 
--disable-zip 
--disable-zlib 
--with-openssl 
--with-gmp 
--without-dom 
--without-readline 
--without-uncritical-warn-choke 
--without-simplexml 
--without-wddx 
--without-mysqlnd 
--without-gd 
--without-libwebp 
```

**Comment by Wes1262** [comment]
Finally tried on another computer and I get the same error. Without iconv and libxml compilation completes correctly. What could it be?

**Comment by weltling** [comment]
Thanks for the report. I'd have yet some questions. First, I see you use some older toolset, could you check some more current version please? It is true, that the latest upgrade introduced some linker issues, we now use 1411 for the snapshots and dependencies was rebuilt. In other terms, something with Visual Studio 15.3 were expected to work fine. The related branches, especially 7.2, are not released yet, so the decision was made in favor of upgrading the compiler. Also, please be sure you use the latest vc15 dependency packages.

Thanks.

**Comment by Wes1262** [comment]
Please forgive me but I have no idea of what I'm doing. :-P Are you saying I should update visual studio? what i did is check out php 7.2 branch, updated php-sdk and downloaded dependencies via phpsdk_deps, buildconf, configure (the one pasted above) and nmake. Thank you for the help.

**Comment by Wes1262** [comment]
I've updated VS and I got the issue solved. Thank you! \o/

**Comment by weltling** [comment]
Great, everything is fine then :) Closing as no issue.

Thanks
