### ISSUE TITLE
Bad build ID when compiling standalone extension on 7.2

### ISSUE THREAD

**Issue by nicolas-grekas** [OSTC/php-sdk-binary-tools#24]
Hello,

I have a build process to compile an extension directly, without requiring to compile the full PHP src at the same time. This works well from 5.4 to 7.1, but fails with 7.2: the DLL is correctly created, but when I try to load it with a php 7.2 downloaded from windows.php.net, it fails with the following message. I'd need a hint to move forward... Would anyone know what is wrong?
Thanks in advance for any help you could provide.

```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.5.1
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall] Environment initialized for: 'x86'
PHP Warning:  PHP Startup: blackfire: Unable to initialize module
Module compiled with build ID=API20170718,TS,19.12.25830.2
PHP    compiled with build ID=API20170718,TS,VC15
```

**Comment by Jerry-Shaw** [comment]
@nicolas-grekas update your PHP src, new VS version has been added, or, it'll be not defined when using VS 15.5.1.

**Comment by weltling** [comment]
Thanks for the report. The new release cycle of Visual Studio is faster now, that's the only reason. The 7.2.0 GA from windows.php.net was likely compiled with the toolset 1911 or lower, now 1912 came out recently which you use.  The new toolset was added to the known versions here https://github.com/php/php-src/commit/2d7bea04624f47d38b190bb46074b5386aa75f6d , but of course the scheme how it is used in PHP for years now needs to be synced more often and older PHP releases might not contain all the known and tested compiler versions.

As a solution, the simplest is probably you to apply the aforementioned patch to 7.2.0. Another possibility could be to use a lower toolset version that is known to the release script. The toolset version 1912 is used for 7.2.1RC1 right now, so it is still under QA. The 19XX versions should be compatible, at least that's the promise. The QA is a must anyway, as there are also new features that move faster. If there are no issues, 7.2.1 should have this toolset version as known anyway.

Thanks.

**Comment by nicolas-grekas** [comment]
OK, thank you very much for the hints!
