### ISSUE TITLE
Argument 1 passed to SDK\Cache::__construct() must be of the type string

### ISSUE THREAD

**Issue by uuf6429** [OSTC/php-sdk-binary-tools#27]
I've been trying to update deps this last 30 minutes with various variations of:
```bash
phpsdk_deps --update --branch master
```
Nothing seems to work though - for some reason nothing can be detected - current CRT, architecture or even PHP branch.

My current project structure looks like so:
```
C:\php-sdk - this git repo on tag php-sdk-2.1.3
C:\php-sdk\phpmaster\
C:\php-sdk\phpmaster\vc15\x64\deps - dependencies (from some earlier install?)
C:\php-sdk\phpmaster\vc15\x64\php-src - git repo of https://github.com/php/php-src on branch PHP-7.2.4
```
Visual Studio 2017 Community v15.6.5

----

What I did originally:
1. I had this system set up already (with instructions from the readme file)
2. I opened cmd prompt in `C:\php-sdk`
3. I ran `phpsdk-vc15-x64.bat`
4. I ran `phpsdk_buildtree phpmaster` (just in case) - it simply complained that dirs already exist
5. I ran `phpsdk_deps --update --branch master` and got the error mentioned in the title

**Comment by uuf6429** [comment]
Aha, one has to be specifically inside the `php-src` directory for it to work. I actually was in the `php-sdk`, `phpmaster` or `phpmaster\vc15\x64` one.

Maybe a quick start up check might help? Even if it doesn't automatically figure out the correct path, maybe show a friendlier error message if a well-known file in php-src doesn't exist in the current directory, eg;
```php
if (!file_exists('php.gif')) throw new Exception('It appears you\'re not inside a php-src directory.');
```

**Comment by weltling** [comment]
Thanks for the report. There is no way to automatically determine the desired configuration. Either it needs to be specified by an option, or read from the current php-src. If you have some patch, please file a PR.

Thanks.
