### ISSUE TITLE
phpsdk-vc15-x64.bat does not detach after calling

### ISSUE THREAD

**Issue by kohldampfer** [OSTC/php-sdk-binary-tools#29]
I am writing a script, which should compile PHP 7.2 on a Windows system in an automatic way. So, whenever there is a new version for PHP 7.2, I do not have to do all this stuff by hand. For this, I am using batch. But after calling phpsdk-vc15-x64.bat, I get this output and my script does not go on:

> [vcvarsall.bat] Environment initialized for: 'x64'
> 
> PHP SDK 2.1.5-dev
> 
> OS architecture:    64-bit
> Build architecture: 64-bit
> Visual C++:         15
> PHP-SDK path:       D:\some\path\to\php7.2\build\deps
> 
> D:\some\path\to\php7.2\build
> $

In my batch file, there is this written:

```
:: ...
set "PHP_SDK_X64=%PHP_DEPS%\phpsdk-vc15-x64.bat"
:: ...
call "%PHP_SDK_X64%"

```

It does not matter, what I am writing after my call of `phpsdk-vc15-x64.bat`, my script stop at the dollar sign `$`. 

Can you give me a way how to handle this problem? This seems to be a bug for me.

**Comment by kohldampfer** [comment]
I just looked, where this problem might come from. I found out, when I change the last line in the file `phpsdk_dumpenv.bat` from

`exit /b %errorlevel%`

to 

`exit %errorlevel%`

then the script does not stop with a dollar sign.

**Comment by weltling** [comment]
Thanks for the question. The script `phpsdk-vc15-x64.bat` is not suitable for the automation. Its purpose is to start a new persistent shell with all the environment setup. The correct script for automtion is `phpsdk-starter.bat`, where a task script can be passed with the `-t` option.  There's an example script in the doc directory, the AppVeyor stuff in the core is also useful to check.

Thanks.

**Comment by kohldampfer** [comment]
@weltling Thanks for your answer. It helped me to solve my problem. Now, I can compile PHP7.2.
