### ISSUE TITLE
Take external openssl

### ISSUE THREAD

**Issue by kohldampfer** [OSTC/php-sdk-binary-tools#30]
The command `phpsdk_deps --update --branch master` downloads several dependencies of PHP7.2. One of them is *OpenSSL*. During normal compilation of PHP7.2, it would use the *OpenSSL* version taken from the `phpsdk_deps` command.

I have compiled *OpenSSL* on my own and I want to use this version as a dependency. Is it somehow possible, to use another *OpenSSL* version and not the one taken from the `phpsdk_deps` command?

**Comment by weltling** [comment]
Custom builds of any package can be used, of course. Simplest were to remove the delivered files for that package and put yours instead manually. With OpenSSL, I guess it needs to be slightly more than that. There are other packages that depend on OpenSSL - fe cURL, ldap, etc. If your desired OpenSSL version is not binary compatible with the one we use officially, you'll likely to end up with having to rebuild all those depending packages, too. Also, if you're going to use PHP as Apache module, it'll be likely another part of the adventure, depending on which Apache binaries you use.

The dependency process in the SDK is quite simple, all the packages are fetched for the given branch. An option could be implemented, so some package is omited. Say there were something similar to `--exclude=item0,item1[,...]`. In some case, such an option could be useful. Another option could be, to provide a way to fetch dependencies from a custom URL. Anyway, those are probably waiting to be implemented, was not asked till now.

Thanks.

**Comment by kohldampfer** [comment]
You wrote

> If your desired OpenSSL version is not binary compatible with the one we use officially, you'll likely to end up with having to rebuild all those depending packages, too.

What do you mean with *binary compatible*? Should it be the exact same version? Or is it OK to use any OpenSSL 1.1.0X version?

**Comment by weltling** [comment]
Specifically about PHP 7.2 - OpenSSL 1.1.0 is used for all the other core deps. Default shared build with static extensions and AppLink. If you build it a similar way, the chances for compatibility of the OpenSSL binaries themselves are good. It also depends on how you build PHP, as some constellations might require additional adjustments the official deps don't provide, or it might require additional fixes.

OpenSSL 1.1.1 might be used in the future, when it's released. Regarding the binary compatibility also, please check https://www.openssl.org/policies/releasestrat.html .

Thanks.

**Comment by weltling** [comment]
The issue seems resolved, thus closing.

Thanks.
