### ISSUE TITLE
Active CRT 'vc15' differs from the branch CRT 'vc14'

### ISSUE THREAD

**Issue by argosback** [OSTC/php-sdk-binary-tools#32]
When I try to get the deps for PHP 7.0.30 I get the message:

```
Fatal error: Uncaught SDK\Exception: Active CRT 'vc15' differs from the branch CRT 'vc14'. in C:\php-sdk\bin\phpsdk_deps.php:131
Stack trace:
#0 {main}
  thrown in C:\php-sdk\bin\phpsdk_deps.php on line 131
```
This windows is running inside a VMware and is a fresh install.

My specs are:

```
OS: Windowx 10 Pro x64
Visual Studio 2017 Community

$ phpsdk-vc15-x86.bat
[vcvarsall.bat] Environment initialized for: 'x86'

PHP SDK 2.1.5

OS architecture:    64-bit
Build architecture: 32-bit
Visual C++:         15
PHP-SDK path:       C:\php-sdk
```

**Comment by weltling** [comment]
Thanks for the report. The 7.0 branch is officially built using Visual Studio 2015. All the dependencies are linked with that CRT. Please also note, that the new SDK is documented for PHP 7.2. While vc15 is documented to be backward compatible to vc14, the only tested constellation for the 7.0 branch is as mentioned - use vc14 dependencies and build with vc14 compiler. You probably could add `--force` to still use vc14 dependencies but use the vc15 tool set, however in that case you'll end up with an untested result. The documentation on Visual Studio 2017 tells it's allowed, however the official PHP builds go by a straight separation of runtimes.

Thanks.
