### ISSUE TITLE
Not building any more because of updated libiconv dependency

### ISSUE THREAD

**Issue by AlexanderGabriel** [OSTC/php-sdk-binary-tools#38]
Hi,

I can't build php any more using current master branch dependencies.
Today, libiconv got updated at https://windows.php.net/downloads/php-sdk/deps/vc15/x64/:
 6/24/2018 10:42 AM      3503092 libiconv-1.15-2-vc15-x64.zip

Last night, building was still possible but now i get an error.
If i use deps vom branch 7.2, it still works.
I use VS 2017 Community Edition on Windows 10 x64 and try to build PHP x64 TS from current master branch.

Here's output of nmake snap:
> C:\dev\work\php-sdk\phpmaster\vc15\x64\php-src
> $ nmake snap
> 
> Microsoft (R) Program Maintenance Utility Version 14.13.26129.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> Recreating build dirs
> 
> Microsoft (R) Program Maintenance Utility Version 14.13.26129.0
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> Recreating build dirs
> libiconv_a.lib(iconv1.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
> fatal error C1007: unrecognized flag '-Ot' in 'p2'
> LINK : fatal error LNK1257: code generation failed
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe"' : return code '0x4e9'
> Stop.
> NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\nmake.exe"' : return code '0x2'
> Stop.

![grafik](https://user-images.githubusercontent.com/23343388/41823483-d30088fa-7800-11e8-8538-9d3ecbf896b8.png)

**Comment by weltling** [comment]
Thanks for the report. As a preparation for the next toolset version some packages was upgraded. Please upgrade to Visual Studio 15.7. Alternatively, you can overwrite the conflicting package with its previous version, see https://windows.php.net/downloads/php-sdk/deps/vc15/x64/. 

Thanks.
