### ISSUE TITLE
WshShell.Exec: Access is denied.

### ISSUE THREAD

**Issue by ehsanphp** [OSTC/php-sdk-binary-tools#39]
hi 
 
I have a problem in  installing

on this command : 
$  configure  

error : 
c:\php-sdk\phpmaster\vc15\x64\php-src\configure.js(164, 2) WshShell.Exec: Access is denied.

 And  with this command : 
$ namek 

NMAKE : fatal error U1064: MAKEFILE not found and no target specified
Stop.

**Comment by weltling** [comment]
Thanks for the report. It is not related to the binary SDK, these commands belong to the PHP core. It seems that WSH is blocked on your system, that's what needs to be fixed. In further, please report the core bugs on bugs.php.net

Thanks.
