### ISSUE TITLE
Add bcgen PHP 7 compiler extensions

### ISSUE THREAD

**Issue by vjardin** [OSTC/php-sdk-binary-tools#40]
Please, what is the process to add DLL extensions such as https://github.com/nanosonde/bcgen/ into the build framework ?

**Comment by weltling** [comment]
Thanks for the question. I'm not sure, what the mentioned extension has to do with building PHP. However, if you need it in your build process, please check the docs about the customized setup here https://github.com/Microsoft/php-sdk-binary-tools#custom-environment-setup.

Thanks.
