### ISSUE TITLE
Any plan to update Visual Studio 2015?

### ISSUE THREAD

**Issue by yitam** [OSTC/php-sdk-binary-tools#44]
Concerning Spectre mitigations as in 

https://blogs.msdn.microsoft.com/vcblog/2018/01/15/spectre-mitigations-in-msvc/

The servicing update to VS 2015 Update 3:

https://support.microsoft.com/en-us/help/4338871/visual-studio-2015-update-3-spectre-variant-1-toolset-qspectre

**Comment by weltling** [comment]
Thanks for the ping. It's admittedly not not a SDK issue, but for the PHP core we've been waiting for vc14 to add this option. Not sure about PHP 7.0 as we won't have a lot of QA there and it's going EOL soon, but for 7.1 it'll be of course done.

Thanks.

**Comment by yitam** [comment]
Thanks @weltling 👍 
Yes I'm mainly asking about PHP 7.1.
