### ISSUE TITLE
PGO INIT Error

### ISSUE THREAD

**Issue by ghost** [OSTC/php-sdk-binary-tools#49]
![screenshot_3](https://user-images.githubusercontent.com/9090555/51068387-5b5ccf00-1604-11e9-889d-bfd58ff5241d.png)

phpsdk_pgo --init has error show on image above! after compiling, init the script for pgo building environment, but this error appear! what's happening?

**Comment by weltling** [comment]
Thanks for the report. This is not related to PGO at all. That SSL error is a known issue, which occurs sporadically and is OpenSSL related. Removing `pgo\work` and retrying to init is what I could suggest.

Thanks.

**Comment by ghost** [comment]
OK! Issue resolved ! Thanks
