### ISSUE TITLE
pgo01org: class.php uses PHP 4 style constructors

### ISSUE THREAD

**Issue by cmb69** [OSTC/php-sdk-binary-tools#51]
This may negatively affect the optimization (unless we're expecting such code to be still common). The problem has already [been reported](https://github.com/intel/php_pgo_training_scripts/issues/2), but overall it appears that intel/php_pgo_training_scripts is unmaintained. Maybe we should fork?

**Comment by weltling** [comment]
Thanks for bringing this up. I'm not sure if we can fork it under the Microsoft org, and if we can - whether it's worth the trouble. I'd suggest we consider one of the following

- invent a patch and apply on init, or
- bundle the source, compressed it should be fairly small

Frankly, i'd prefer the first option, as bundling is always something that should be avoided if not strictly necessary.

Thanks.

**Comment by cmb69** [comment]
I've filed intel/php_pgo_training_scripts#3. Maybe it'll be accepted; otherwise we could use it as patch.

**Comment by weltling** [comment]
@cmb69 thanks for filing the PR upstream, but not sure to expect that one to be merged soon :) In might make sense integrating the patch at some point. Or actually not patch, but do a simple search/replace like here https://github.com/Microsoft/php-sdk-binary-tools/blob/master/pgo/cases/pgo01org/TrainingCaseHandler.php#L83. It won't fail, if the PR has been merged anyway.

Thanks.

**Comment by cmb69** [comment]
I've implemented a search and replace workaround as PR #53.

**Comment by weltling** [comment]
PR merged.

Thanks.
