### ISSUE TITLE
PHP 7.4 build failure with default dependencies

### ISSUE THREAD

**Issue by cmb69** [OSTC/php-sdk-binary-tools#52]
PHP 7.4 unbundles liboniguruma, which currently is only available with the *staging* dependencies, but by default the *stable* dependencies are used. Therefore, builds which try to enable mbregex will fail. This is no problem with the rmtools, since these always use *staging* dependencies, but users who are doing their own builds with the plain SDK are likely to stumble over this.

I suggest to either [use *staging* dependencies](https://github.com/Microsoft/php-sdk-binary-tools/blob/60cfe587d5442854c65180b0145702e032b7db4c/lib/php/libsdk/SDK/Config.php#L117-L121) for PHP 7.4 temporarily (until first beta), or to push [libonig](https://github.com/winlibs/oniguruma) to *stable* soon.

**Comment by cmb69** [comment]
Well, we also should do something regarding the [code](https://github.com/Microsoft/php-sdk-binary-tools/blob/60cfe587d5442854c65180b0145702e032b7db4c/lib/php/libsdk/SDK/Config.php#L117-L121) [duplication](https://github.com/Microsoft/php-sdk-binary-tools/blob/60cfe587d5442854c65180b0145702e032b7db4c/bin/phpsdk_deps.php#L135-L139); as it is now, the code in phpsdk_deps.php is unused since ` Config::getCurrentStabilityName()` never returns `null` .

**Comment by weltling** [comment]
It's probably fine adding that to stable, it's been a while libonig was used for the builds and it seems ok. There was something else unbundled, libsqlite? I just lost the outline of that change :) Need to check that and sync to stable as well.

Thanks.

**Comment by cmb69** [comment]
libsqlite3 is unbundled as of PHP 7.4.0 as well, but the dependency is already [in stable](https://windows.php.net/downloads/php-sdk/deps/series/packages-7.4-vc15-x86-stable.txt).

**Comment by weltling** [comment]
All the deps are synchronized now. Please handle the code dup in a separate issue.

Thanks.

**Comment by cmb69** [comment]
> Please handle the code dup in a separate issue.

See PR #54.
