### ISSUE TITLE
Missing msys-crypto-1.1.dll 

### ISSUE THREAD

**Issue by Jan-E** [OSTC/php-sdk-binary-tools#58]
@cmb69 
In https://github.com/Microsoft/php-sdk-binary-tools/commit/51d2eaa4631a69979ef842149023bb467ce8e956 msys-crypto-1.1.dll was not included. Any call to wget will fail:

![wget](https://user-images.githubusercontent.com/1757825/56216349-8fabb580-6061-11e9-8097-a672eec93634.png)

**Comment by Jan-E** [comment]
msys-crypto-1.0.0.dll and msys-ssl-1.0.0.dll are still in https://github.com/Microsoft/php-sdk-binary-tools/tree/master/msys2/usr/bin

msys-gcc_s-1.dll seems an old version too.

**Comment by cmb69** [comment]
ACK. Apparently, when I've updated with pacman, something went wrong. I'm working on it. Thanks for reporting @Jan-E!

**Comment by Jan-E** [comment]
Thx. I ran into it while building the RC1's that are already available on https://github.com/php/php-src/releases

**Comment by cmb69** [comment]
Hmm, it seems that msys2 [wget with OpenSLL 1.1 is broken](https://github.com/msys2/MINGW-packages/issues/4458):
````
wget https://www.php.net/manual/en/index.php
--2019-04-16 17:16:31--  https://www.php.net/manual/en/index.php
Disabling SSL due to encountered errors.
````
(the actual URI doesn't matter)

Seems we have to downgrade wget to 1.19.4 (latest working with OpenSSL 1.0), until the issue is solved in msys2.

**Comment by Jan-E** [comment]
Looks like 1.20 will also do the job:
https://eternallybored.org/misc/wget/

**Comment by cmb69** [comment]
@Jan-E I'd rather not mix this with the msys2 binaries.

**Comment by Jan-E** [comment]
No, but this might indicate that Wget with OpenSSL 1.1.1a still works. If there is a msys2 version with that one...

**Comment by cmb69** [comment]
I'd checked the packages on http://repo.msys2.org/msys/x86_64/, but all wget 1.20.X require OpenSSL 1.1.1b, and wget 1.19.5 requires OpenSSL 1.0.2o. Seems we're out of luck.

**Comment by Jan-E** [comment]
OK. I saw your PR https://github.com/Microsoft/php-sdk-binary-tools/pull/59
Seems you have to sign something, but this issue can be closed again.

**Comment by cmb69** [comment]
@msftclas is confused; I already have commit rights to this repo, but I'm always asked to sign a CLA for PRs.
