### ISSUE TITLE
no genera librerias dll

### ISSUE THREAD

**Issue by JHONF2078** [OSTC/php-sdk-binary-tools#61]
no se genera ninguna  libreria dll cuando se ejecuta el comando --with-library_name=shared (ejemplo ibm_db2  y  pdo_ibm )

**Comment by cmb69** [comment]
Please check the output of `configure …` for related (error) messages.

**Comment by weltling** [comment]
This is not an SDK issue. A ticket should be filed against the corresponding PECL package.

Thanks.
