### ISSUE TITLE
Could not found vc15 folder. 

### ISSUE THREAD

**Issue by arshidkv12** [OSTC/php-sdk-binary-tools#64]
I am getting error "could not found vc15 folder". 
How to resolve it ?
I installed visual studio 2019 community edition.

**Comment by cmb69** [comment]
If you want to compile with VS 2019, you have to start phpsdk-vs16-x64.bat or phpsdk-vs16-x86.bat. See also the [general instructions](https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2).

**Comment by arshidkv12** [comment]
Same error "vs16 folder not found error".

**Comment by cmb69** [comment]
Are you using php-sdk-2.2.0? If so, what's the exact error message?

**Comment by arshidkv12** [comment]
I did check out from master branch.

**Comment by cmb69** [comment]
Okay, master HEAD should be fine as well. Please try `bin\vswhere  -nologo -version [16,17) -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -format text`

What does it print?

**Comment by arshidkv12** [comment]
Visual Studio Locator version 2.6.7+91f4c1d09e [query version
2.1.1046.44959]
Copyright (C) Microsoft Corporation. All rights reserved.

instanceId: 69ecbfa8
installDate: 05-09-2019 17:15:22
installationName: VisualStudio/16.2.3+29215.179
installationPath: C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community
installationVersion: 16.2.29215.179
productId: Microsoft.VisualStudio.Product.Community
productPath: C:\Program Files (x86)\Microsoft Visual
Studio\2019\Community\Common7\IDE\devenv.exe
state: 4294967295
isComplete: 1
isLaunchable: 1
isPrerelease: 0
isRebootRequired: 0
displayName: Visual Studio Community 2019
description: Free, fully-featured IDE for students, open-source and
individual developers
channelId: VisualStudio.16.Release
channelUri: https://aka.ms/vs/16/release/channel
enginePath: C:\Program Files (x86)\Microsoft Visual
Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service
releaseNotes: https://go.microsoft.com/fwlink/?LinkId=660893#16.2.3
thirdPartyNotices: https://go.microsoft.com/fwlink/?LinkId=660909
updateDate: 2019-09-05T11:45:22.2989437Z
catalog_buildBranch: d16.2
catalog_buildVersion: 16.2.29215.179
catalog_id: VisualStudio/16.2.3+29215.179
catalog_localBuild: build-lab
catalog_manifestName: VisualStudio
catalog_manifestType: installer
catalog_productDisplayVersion: 16.2.3
catalog_productLine: Dev16
catalog_productLineVersion: 2019
catalog_productMilestone: RTW
catalog_productMilestoneIsPreRelease: False
catalog_productName: Visual Studio
catalog_productPatchVersion: 3
catalog_productPreReleaseMilestoneSuffix: 1.0
catalog_productSemanticVersion: 16.2.3+29215.179
catalog_requiredEngineVersion: 2.2.3074.64249
properties_campaignId: 1942769013.1567676919
properties_canceled: 0
properties_channelManifestId: VisualStudio.16.Release/16.2.3+29215.179
properties_nickname:

**Comment by cmb69** [comment]
Thanks. I'm assuming that this is the output of plain `bin\vswhere`, and that the full command given above would produce:
````
installationPath: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
````
Then there should be a folder C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC, which is apparently missing. Did you actually [select C++ support](https://docs.microsoft.com/de-de/cpp/build/vscpp-step-0-installation?view=vs-2019) when installing Visual Studio?

**Comment by arshidkv12** [comment]
I think, I didn't selected c++.
 How to resolve it?

Regards

**Comment by cmb69** [comment]
https://docs.microsoft.com/de-de/cpp/build/vscpp-step-0-installation?view=vs-2019

**Comment by arshidkv12** [comment]
Thank you

**Comment by arshidkv12** [comment]
I have one more doubt, I want to compile against vc14, vc15, vs16. How can I ?

**Comment by arshidkv12** [comment]
I am getting the following error when I load the extension in mine PHP.

```
PHP Warning: PHP Startup: gd: Unable to initialize module
Module compiled with build ID=API20180731,NTS,VC15
PHP compiled with build ID=API20180731,TS,19.22.27905
These options need to match
in Unknown on line 0

Warning: PHP Startup: gd: Unable to initialize module
Module compiled with build ID=API20180731,NTS,VC15
PHP compiled with build ID=API20180731,TS,19.22.27905
These options need to match
in Unknown on line 0
```

**Comment by cmb69** [comment]
> I have one more doubt, I want to compile against vc14, vc15, vs16. How can I ?

You can install multiple Visual Studio versions on the same computer. PHP-SDK is supposed to be able to handle that.

> ````
>Module compiled with build ID=API20180731,NTS,VC15
>PHP compiled with build ID=API20180731,TS,19.22.27905
>````

You need matching PHP and extension builds (NTS vs. TS and proper Visual Studio version).

Anyhow, apparently the original issue has been resolved, so I'm closing this ticket.
