### ISSUE TITLE
It does not support gdb debug.

### ISSUE THREAD

**Issue by toxmc** [OSTC/php-sdk-binary-tools#65]
I'm very sorry to bother you.
I was used PHP-SDK compiled DEBUG PHP. But it does not support GDB debug.
```
nmake clean 
buildconf
configure --disable-all  --enable-cli --with-all-shared  --enable-test --disable-zts --enable-debug
nmake
```
![image](https://user-images.githubusercontent.com/3990846/66972714-09336780-f0c8-11e9-8d95-b56c9dabc028.png)
![image](https://user-images.githubusercontent.com/3990846/66973255-fcb00e80-f0c9-11e9-8b61-91017b46208b.png)

How can I do to debug PHP_SDK compiled PHP use GDB?
thanks.

**Comment by cmb69** [comment]
I don't think that you can debug using GDB, but you can use Visual Studio for debugging.

**Comment by toxmc** [comment]
ok, thanks.
