### ISSUE TITLE
Trying to Create My own Extension 

### ISSUE THREAD

**Issue by DDAmine** [OSTC/php-sdk-binary-tools#68]
i m trying to make my own extension but when i execute "nmake"    it says enable to found "Myextesion.c " is there away to make the compiler generate the "Myextesion.c "  for me or i have to created myself 
ps: i m trying to avoid re-implementing the modules on c

**Comment by cmb69** [comment]
See http://www.phpinternalsbook.com/ on how to write PHP extensions. See https://www.php.net/support on where to ask for help. Thanks.

**Comment by DDAmine** [comment]
i did @cmb69  but i m working on windows not linux 
i just wanna know if i can generate my extension without writing the "******.c" files 
if there's a way to make the compiler make them , cause i have the code in php and i want to make it a "***.dll" and i have no c knowledge and thx

**Comment by cmb69** [comment]
PHP extensions are written in C, not PHP, and there is no way to translate PHP to C.
