### ISSUE TITLE
Symfony

### ISSUE THREAD

**Issue by ghost** [OSTC/php-sdk-binary-tools#73]
![image](https://user-images.githubusercontent.com/47756883/106392741-fedad100-63d1-11eb-8b84-4c377a99a961.png)
![image](https://user-images.githubusercontent.com/47756883/106392768-25990780-63d2-11eb-9aee-6376b38317a9.png)

The site of download symfony,phar is down!!! phpsdk_pgo --init have a error !!!!

**Comment by cmb69** [comment]
AFAIK, the `symfony_demo` training case is supposed to run with Symfony 3.x, which is useful for old versions, but apparently the phar based installation is no longer supported. For now, just disabling this training case appears to be reasonable (see PR #74). It needs to be decided whether a training case for Symfony with SQLite3 should be retained, or whether the already existing `symfony_demo_pdo_mysql` (obviously Symfony with MySQL) is sufficient.
