### ISSUE TITLE
Could not determine 'vs16' directory

### ISSUE THREAD

**Issue by tsioureth** [OSTC/php-sdk-binary-tools#78]
Hi,

I apologize in advance, since I'm pretty new to all of this. It might just be a newbie issue.

I had a pop-up error on VS code, saying that I had to indicate the exe's path oh php in the settings. After reading some docs and forum, I landed on the page to [set up php on Widows](https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2).

As written, I've extracted `php-sdk-binary-tools-master.zip` in `C:\php-sdk`. I'm running on Windows 10 Professional 21H1 x 64, so I choose to invoke phpsdk-vs16-x64.bat with Powershell. And this returns me :
`Could not determine 'vs16' directory`

What should I do in order to continue ?

**Comment by cmb69** [comment]
Do you really want to *build* your own PHP on Windows, or is it just about *using* PHP on Windows? If the latter, see https://www.php.net/manual/en/install.windows.php (in short, download the desired PHP version from https://windows.php.net/download, unzip to, say C:\php, and tell VSCode the path).

**Comment by tsioureth** [comment]
Oh ok, I get it. I've mixed up things between the PHP Source, the php-sdk-binary-tool, and the "ready-to-use" .zip you can download from [https://windows.php.net/download](https://windows.php.net/download).

Indeed, I'm just trying to use PHP on Windows. I've spotted the php.exe in the downloaded file, so I could copy/paste the path, as indicated here : [https://code.visualstudio.com/docs/languages/php](https://code.visualstudio.com/docs/languages/php)

Thank you for your help !
