### ISSUE TITLE
How to choose vs 2017 when execute phpsdk-vc15-x64.bat?

### ISSUE THREAD

**Issue by huanghantao** [OSTC/php-sdk-binary-tools#79]
I installed `VS2017` and `VS2019` at the same time, and when I finished executing `phpsdk-vc15-x64.bat`, I found that it chose `VS2019` by default:

```bash
which cl.exe
/cygdrive/c/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/HostX64/x64/cl.exe
```

**Comment by cmb69** [comment]
Cygwin is probably not supported. Does it work if you use phpsdk-vc15-x64.bat or phpsdk-vc15-x86.bat to start a cmd shell? `where cl.exe` reports the desired Visual Studio 2017 for me.

**Comment by pierrejoye** [comment]
I would suggest to always open a vs dev command line.

**Comment by cmb69** [comment]
> I would suggest to always open a vs dev command line.

This shouldn't be necessary with somewhat recent versions of the PHP-SDK, since there is some quite elaborate code to detect the desired VS version. This should work even for different editions of Visual Studio, e.g. VS 2017 Enterprise and VS 2019 Community.

**Comment by pierrejoye** [comment]
ah nice, when I wrote it there were always edge cases not working well
outside it.

Also now the SDKs are cleaner. :)

**Comment by cmb69** [comment]
For recent VS versions, we can rely on vswhere.exe instead of probing the registry. :)

**Comment by pierrejoye** [comment]
for 2017 or newer yes.

There is another before but I can't find it back  :)

**Comment by huanghantao** [comment]
Thank you. According to your tips, the problem has been solved.
