### ISSUE TITLE
vswhere fails to locate VS Community 2017

### ISSUE THREAD

**Issue by cmb69** [OSTC/php-sdk-binary-tools#8]
I have installed Microsoft Visual Studio Community 2017 (Version 15.1 (26403.3) Release). Running either phpsdk-vc15-x86.bat or phpsdk-vc15-x64.bat yields:
````
Das System kann den angegebenen Pfad nicht finden.
````
I've tracked that down to the [respective vswhere call](https://github.com/OSTC/php-sdk-binary-tools/blob/php-sdk-2.0.0/bin/phpsdk_setshell.bat#L62). Running the following directly:
````
vswhere -nologo -version 15 -requires Microsoft.VisualStudio.Component.VC.Tools.x86.x64 -property installationPath -format text
````
prints nothing, so that `PHP_SDK_VC_DIR` is empty.

However, running
````
vswhere -nologo -version 15 -property installationPath -format text
````
yields `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community` which exists, but there is no `VC` folder in it.

**Comment by weltling** [comment]
Is the VC++ component installed?

Thanks.

**Comment by cmb69** [comment]
Thanks, that's it. Stupid me! :) Sorry for the noise.
