### ISSUE TITLE
when a path is contains blank spaces,bat execution failure 

### ISSUE THREAD

**Issue by tyonly** [OSTC/php-sdk-binary-tools#81]
a file path include blank spaces .example: c:\program files\
execute "phpsdk-vc15-x64.bat"

error message: 不是内部或外部命令，也不是可运行的程序

**Comment by tyonly** [comment]
source code "call %~dp0phpsdk-starter.bat -c vs16 -a x64 %*"
can fix with :  call "%~dp0"phpsdk-starter.bat -c vs16 -a x64 %*

**Comment by cmb69** [comment]
I'm not sure it would make sense to fix that; there may be more issues with spaces in the path (AFAIK, php-src can't handle these either). Furthermore, it is suggested to install the PHP SDK binary tools [in the shortest possible path](https://github.com/microsoft/php-sdk-binary-tools#usage).

**Comment by tyonly** [comment]
OK,I change my clone folder to f:\sdk , no longer contains spaces

**Comment by pierrejoye** [comment]
also it could use the bat macro to replace the path with the 8.3 format.

**Comment by tyonly** [comment]
> the path with the 8.3 format.

I clone the git zip to a path like: d:\abc d\01 aa\03 dd\, then execute : phpsdk-vc15-x64.bat ,it display errors.  then I follow `cmb69`'s suggest ,change my foloder path, then it works.   tks all

**Comment by pierrejoye** [comment]
What I mean is using %%~sf macro to transform the "c:\path with some\spaces" to the 8.3 format.

for example:

```
C:\>cd "\Program Files"
C:\Program Files>for %f in ("%cd%") do @echo %~sf
C:\PROGRA~1
```

can be used in variables etc.

Now, that will work too if the transformed path is used in all include paths and co.
