### ISSUE TITLE
Failed to fetch supported branches

### ISSUE THREAD

**Issue by stuli3** [OSTC/php-sdk-binary-tools#83]
Hi,

I need create a php 8.0.17 build. But I have a fatal error on the phpsdk_deps step.

C:\php-sdk>phpsdk-vs16-x64.bat
[vcvarsall.bat] Environment initialized for: 'x64'

PHP SDK 2.2.1-dev

OS architecture:    x64
Build architecture: x64
Visual C++:         14.29.30141.0
PHP-SDK path:       C:\php-sdk

C:\php-sdk
$ phpsdk_buildtree phpdev

C:\php-sdk\phpdev\vs16\x64
$ cd php-8.0.17-src

C:\php-sdk\phpdev\vs16\x64\php-8.0.17-src
$ phpsdk_deps -u

Fatal error: Uncaught SDK\Exception: Failed to fetch supported branches in C:\php-sdk\lib\php\libsdk\SDK\Config.php:172
Stack trace:
#0 C:\php-sdk\lib\php\libsdk\SDK\Config.php(182): SDK\Config::getKnownBranches()
#1 C:\php-sdk\bin\phpsdk_deps.php(105): SDK\Config::setCurrentBranchName('8.0')
#2 {main}
  thrown in C:\php-sdk\lib\php\libsdk\SDK\Config.php on line 172

**Comment by cmb69** [comment]
I cannot reproduce that with current tip of the master branch, and [php-8.0.17-src.zip](https://windows.php.net/downloads/releases/php-8.0.17-src.zip). Did you unzip php-8.0.17-src.zip correctly; i.e. is there are file buildconf.bat directly in that folder, or in a subfolder?

**Comment by stuli3** [comment]
I think it is correctly. C:\php-sdk\phpdev\vs16\x64\php-8.0.17-src\buildconf.bat

Maybe I did not install any Visual Studio 2019 ingredients? What do you need exactly?

**Comment by cmb69** [comment]
I don't think this is related to missing Visual Studio 2019 components. Anyway, the [requirements are listed in the README](https://github.com/microsoft/php-sdk-binary-tools#requirements).

Anyhow, I have no idea why that fails for you. Consider to debug the script; a good starting point appears to be [Config::getKnownBranches()](https://github.com/microsoft/php-sdk-binary-tools/blob/1bb6a4adb5633760d241140ada4dfac3b8d8d2f3/lib/php/libsdk/SDK/Config.php#L135).

**Comment by stuli3** [comment]
Maybe it just doesn't work because of a proxy. I downloaded the files manually.
Thanks!
